name: tranzit_app
description: "Приложение для отображения групп Tranzit."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0-323.2.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Сетевые запросы
  dio: ^5.4.0
  internet_connection_checker: ^1.0.0+1
  
  # Управление состоянием
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  
  # Генерация кода
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # Навигация
  go_router: ^13.2.0
  
  # Локальное хранилище
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  
  # Утилиты
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.7
  url_launcher: ^6.2.5
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  package_info_plus: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  bloc_test: ^9.1.4
  
  # Генераторы кода
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/